calendarManagement/urls.py
from django.urls import path, include
from .views import calendar,delete_calendar


app_name = "calendar_urls"
urlpatterns = [
    path('',calendar, name="calendar"),
    path('delete/<int:id>/^',delete_calendar, name="delete_calendar"),
    # path('create/new/^',new_message_view, name="new_message"),
]

caseManagement/urls.py
from django.urls import path, include
from .views import case_view,case_details_view,new_case_view
from django.conf import settings
from django.views.static import serve



app_name = "case_urls"
urlpatterns = [
    path('',case_view, name="case"),
    path('create/new/^',new_case_view, name="new_case"),
    path('<int:pk>/detail/^',case_details_view, name="case_detail"),
    path(r'^download/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

lex/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userManagement.urls')),
    path('case/', include(('caseManagement.urls', 'cases'),namespace='case_urls')),
    path('calendar/', include(('calendarManagement.urls', 'calendars'),namespace='calendar_urls')),
    path('message/', include(('messageManagement.urls', 'messages'),namespace='message_urls')),
    path('accounts/', include('allauth.urls')),
      
] 


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messageManagement/urls.py
from django.urls import path, include
from .views import new_message_view,message_view


app_name = "message_urls"
urlpatterns = [
    path('',message_view, name="message"),
    path('create/new/^',new_message_view, name="new_message"),
]

messageManagement/models.py
from django.db import models
from caseManagement.models import Case
from django.contrib.auth import  get_user_model


# reference to the User database object
User = get_user_model()




STATUS = (
        ('unread','unread'),
        ('read','read'),
)

# Case message database fields
class Message(models.Model):
    title = models.CharField(max_length=150)
    message = models.CharField(max_length=3050)
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(choices=STATUS, default="unread", max_length=150)



# User message database fields
class UserMessage(models.Model):
    title = models.CharField(max_length=150)
    message = models.CharField(max_length=3050)
    receiver = models.IntegerField()
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(choices=STATUS, default="unread", max_length=150)

messageManagement/views.py
from django.shortcuts import render
from caseManagement.models import Case
from .models import Message, UserMessage
from django.shortcuts import redirect
from django.contrib.auth import get_user_model

# Create your views here.

# reference to the User database object
User = get_user_model()

# this function returns the create message page
def new_message_view(request):
    # get all cases from the database
    case = Case.objects.all()
    # get all messages from the database
    msgObj = Message.objects.all()
    userMsgObj = UserMessage.objects.all()
    # checks if the http request is a post request
    if request.POST:
        # gets the values passed in the request object
        case_id = request.POST.get('case_id')
        title = request.POST.get('title')
        message = request.POST.get('message')
    # checks if the user is authenticated
        if 'user' not in request.session:
            user = request.user.id
        else:  
            user = request.session['user']
        # get the sender of the message from the database
        sender = User.objects.get(pk=user)
        # get the case object from the database
        case = Case.objects.get(pk=case_id)
        # save the message to the database
        msg = Message(title=title, message=message, case=case, sender=sender)
        msg.save()
        # return the message page
        return redirect('/message/')
    # return create message page
    return render(request, "newMessage.html", {'case': case,"msgs": msgObj, "userMsgs":userMsgObj})


# this function returns the message page with all messages
def message_view(request):
    # checks if the user is authenticated
    if 'user' in request.session:
        user = request.session['user']
    else:
        user = request.user.id
        # get all user message from database in descending order
    userMsgObj = UserMessage.objects.all().order_by('id')
    # mark message as read
    caseObj = Case.objects.filter(creator=user)
    for case in caseObj:
        Message.objects.filter(case=case).update(status="read")
    # end
    # gets a particular user id from a database
    userObj = User.objects.get(pk=user)
    # gets all case messages in descending order
    msgObj = Message.objects.all().order_by('-id')
    # return message web page
    return render(request, "message.html", {
        "msgs": msgObj,
        "user": userObj,
        "userMsgs":userMsgObj
    })

messageManagement/templates/message.html
<!-- <a href="{% url 'case_urls:new_case' %}">create  a new case</a> -->

<!DOCTYPE html>
{% load static%}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Lex Atrium</title>
    <meta content="" name="description">
    <meta content="" name="keywords">


    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <link href='{% static "vendor/bootstrap/css/bootstrap.min.css" %}' rel="stylesheet">
    <link href='{% static "vendor/bootstrap-icons/bootstrap-icons.css" %}' rel="stylesheet">
    <link href='{% static "vendor/boxicons/css/boxicons.min.css" %}' rel="stylesheet">

    <link href='{% static "css/dashboard.css"  %}' rel="stylesheet">















</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
            <a href="#" class="logo d-flex align-items-center">
                <span class="d-none d-lg-block">LEX-ATRIUM </span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div><!-- End Logo -->

        <div class="search-bar">
            <form class="search-form d-flex align-items-center" method="POST" action="#">
                <input type="text" name="query" placeholder="Search" title="Enter search keyword">
                <button type="submit" title="Search"><i class="bi bi-search"></i></button>
            </form>
        </div><!-- End Search Bar -->

        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">

                <li class="nav-item d-block d-lg-none">
                    <a class="nav-link nav-icon search-bar-toggle " href="#">
                        <i class="bi bi-search"></i>
                    </a>
                </li><!-- End Search Icon-->

                <li class="nav-item dropdown">

                    <a class="nav-link nav-icon" href="" data-bs-toggle="dropdown">
                        <i class="bi bi-bell"></i>

                        {% if user.role == "judge" %}

                        {% for umsg in userMsgs %}
                        {% if umsg.receiver == user.id and umsg.status == "unread" %}
                        <span class="badge bg-primary badge-number">

                            {{umsg|length}}

                        </span>

                        {% endif %}
                        {% endfor %}

                        {% else %}

                        {% for msg in msgs %}
                        {% if msg.case.creator.id == user.id and msg.status == "unread" %}
                        <span class="badge bg-primary badge-number">

                            {{msg|length}}
                        </span>
                        {% endif %}
                        {% endfor %}

                        {% endif %}

                    </a><!-- End Notification Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">

                        {% if user.role == "judge" %}
                        {% for umsg in userMsgs %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        {% if umsg.receiver == user.id and umsg.status == "unread" %}

                        <li class="notification-item">
                            <i class="bi bi-exclamation-circle text-warning"></i>
                            <a href="/message/">
                                <div>
                                    <h4>{{umsg.title}}</h4>
                                    <p>{{umsg.message}}</p>
                                    <p></p>
                                </div>
                            </a>
                        </li>


                        {%endif%}

                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        {%endfor%}

                        {% else %}
                        {% for msg in msgs %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        {% if msg.case.creator.id == user.id and msg.status == "unread" %}

                        <li class="notification-item">
                            <i class="bi bi-exclamation-circle text-warning"></i>
                            <a href="/message/">
                                <div>
                                    <h4>{{msg.title}}</h4>
                                    <p>{{msg.message}}</p>
                                    <p></p>
                                </div>
                            </a>
                        </li>


                        {%endif%}

                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        {%endfor%}
                        {%endif%}


                        <!-- <li>
                        <hr class="dropdown-divider">
                      </li>
                      <li class="dropdown-footer">
                        <a href="#">Show all notifications</a>
                      </li> -->

                    </ul><!-- End Notification Dropdown Items -->

                </li><!-- End Notification Nav -->


                <li class="nav-item dropdown pe-3">

                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <!-- <img src="assets/img/profile-img.jpg" alt="Profile" class="rounded-circle"> -->
                        <i class="bi bi-person"></i>
                        <!-- <span class="d-none d-md-block dropdown-toggle ps-2">NO.{{user.call_to_bar_number }}</span> -->
                    </a><!-- End Profile Iamge Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li class="dropdown-header">
                            <h6>{{user.first_name}} {{user.last_name}}</h6>
                            <span>{{user.role}}</span>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="/logout/">
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Sign Out</span>
                            </a>
                        </li>

                    </ul><!-- End Profile Dropdown Items -->
                </li><!-- End Profile Nav -->

            </ul>
        </nav><!-- End Icons Navigation -->

    </header><!-- End Header -->





    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item">
                <a class="nav-link " href="/">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li><!-- End Dashboard Nav -->

            <li class="nav-item">
                <a class="nav-link" href="{% url 'case_urls:case' %}">
                    <i class="bi bi-folder"></i>
                    <span>Cases</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'message_urls:message' %}">
                    <i class="bi bi-chat"></i>
                    <span>Message</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'calendar_urls:calendar' %}">
                    <i class="bi bi-calendar"></i>
                    <span>Calendar</span>
                </a>
            </li>
            <br><br>

            <li class="nav-item">
                <a class="nav-link" href="/settings/">

                    <i class="bi bi-wrench"></i>
                    <span>Settings</span>
                </a>
            </li>


        </ul>

    </aside>
    <!-- End Sidebar-->




    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Message</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item active">Message</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->





        <div class="card">
            <div class="card-body p-5">

                <!-- Main Massege <a href="{% url 'message_urls:new_message' %}">New Message</a> -->



                <h5 class="card-title">All Messages</h5>

                <!-- Accordion without outline borders -->
                <div class="accordion accordion-flush" id="accordionFlushExample">


                    {% if user.role == "judge" %}

                    {%for umsg in userMsgs %}
                    {% if umsg.receiver == user.id %}
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="{{umsg.id}}">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#flush-collapse{{umsg.id}}" aria-expanded="false"
                                aria-controls="flush-collapse{{umsg.id}}">
                                <b> {{umsg.title}}</b>
                            </button>
                        </h2>
                        <div id="flush-collapse{{umsg.id}}" class="accordion-collapse collapse"
                            aria-labelledby="{{umsg.id}}" data-bs-parent="#accordionFlushExample">
                            <div class="accordion-body"> {{umsg.message}}</div>
                        </div>
                    </div>
                    {% endif %}

                    {% endfor %}



                    {% elif user.role == "litigant" or user.role == "lawyer" %}
                    {%for msg in msgs %}
                    {% if msg.case.creator.id == user.id %}
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="{{msg.id}}">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#flush-collapse{{msg.id}}" aria-expanded="false"
                                aria-controls="flush-collapse{{msg.id}}">
                                <b> {{msg.title}}</b>
                            </button>
                        </h2>
                        <div id="flush-collapse{{msg.id}}" class="accordion-collapse collapse"
                            aria-labelledby="{{msg.id}}" data-bs-parent="#accordionFlushExample">
                            <div class="accordion-body"> {{msg.message}}</div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}

                    {% else %}
                    {%for msg in msgs %}

                    <div class="accordion-item">
                        <h2 class="accordion-header" id="{{msg.id}}">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#flush-collapse{{msg.id}}" aria-expanded="false"
                                aria-controls="flush-collapse{{msg.id}}">
                                <b> {{msg.title}}</b>
                            </button>
                        </h2>
                        <div id="flush-collapse{{msg.id}}" class="accordion-collapse collapse"
                            aria-labelledby="{{msg.id}}" data-bs-parent="#accordionFlushExample">
                            <div class="accordion-body"> {{msg.message}}</div>
                        </div>
                    </div>


                    {% endfor %}

                    {% endif %}

                </div><!-- End Accordion without outline borders -->


            </div>
        </div>







    </main>
    <!-- End #main -->

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
        <div class="copyright">
            &copy; Copyright <strong><span>LEX-ATRIUM </span></strong>. All Rights Reserved
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <script src='{% static "vendor/bootstrap/js/bootstrap.bundle.js" %}'></script>
    <script src='{% static "vendor/jquery/jquery.min.js" %}'></script>
    <script src='{% static "vendor/select2/select2.min.js"  %}'></script>

    <script src='{% static "js/global.js" %}'></script>


    <script src='{% static "js/dashboard.js" %}'></script>


</body>

</html>

messageManagement/templates/newMessage.html
<!-- <a href="{% url 'case_urls:new_case' %}">create  a new case</a> -->

<!DOCTYPE html>
{% load static%}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Lex Atrium</title>
    <meta content="" name="description">
    <meta content="" name="keywords">


    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
      rel="stylesheet">
  
    <link href='{% static "vendor/bootstrap/css/bootstrap.min.css" %}' rel="stylesheet">
    <link href='{% static "vendor/bootstrap-icons/bootstrap-icons.css" %}' rel="stylesheet">
    <link href='{% static "vendor/boxicons/css/boxicons.min.css" %}' rel="stylesheet">
  
    <link href='{% static "css/dashboard.css"  %}' rel="stylesheet">













</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
            <a href="#" class="logo d-flex align-items-center">
                <span class="d-none d-lg-block">LEX-ATRIUM </span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div><!-- End Logo -->

        <div class="search-bar">
            <form class="search-form d-flex align-items-center" method="POST" action="#">
                <input type="text" name="query" placeholder="Search" title="Enter search keyword">
                <button type="submit" title="Search"><i class="bi bi-search"></i></button>
            </form>
        </div><!-- End Search Bar -->

        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">

                <li class="nav-item d-block d-lg-none">
                    <a class="nav-link nav-icon search-bar-toggle " href="#">
                        <i class="bi bi-search"></i>
                    </a>
                </li><!-- End Search Icon-->

                <li class="nav-item dropdown">

                    <a class="nav-link nav-icon" href="" data-bs-toggle="dropdown">
                      <i class="bi bi-bell"></i>
          
                      <span class="badge bg-primary badge-number">
                        {% for msg in msgs %}
                        {% if msg.case.creator.id == user.id and msg.status == "unread" %}
          
                        {% if msg|length == 0 %}
                        1
                        {% else %}
                        
                        {{msg|length}}
          
                        {%endif%}
          
                        {% endif %}
                        {% endfor %}
          
          
                      </span>
          
                    </a><!-- End Notification Icon -->
          
                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
                      <!-- <li class="dropdown-header">
                        You have 4 new notifications
                        <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
                      </li> -->
                      {% if user.role == "judge" %}
                      {% for umsg in userMsgs %}
                      <li>
                          <hr class="dropdown-divider">
                      </li>

                      {% if umsg.receiver == user.id and umsg.status == "unread" %}

                      <li class="notification-item">
                          <i class="bi bi-exclamation-circle text-warning"></i>
                          <a href="/message/">
                              <div>
                                  <h4>{{umsg.title}}</h4>
                                  <p>{{umsg.message}}</p>
                                  <p></p>
                              </div>
                          </a>
                      </li>
          

                      {%endif%}

                      <li>
                          <hr class="dropdown-divider">
                      </li>
                      {%endfor%}

                      {% else %}
                      {% for msg in msgs %}
                      <li>
                          <hr class="dropdown-divider">
                      </li>

                      {% if msg.case.creator.id == user.id and msg.status == "unread" %}

                      <li class="notification-item">
                          <i class="bi bi-exclamation-circle text-warning"></i>
                          <a href="/message/">
                              <div>
                                  <h4>{{msg.title}}</h4>
                                  <p>{{msg.message}}</p>
                                  <p></p>
                              </div>
                          </a>
                      </li>
              

                      {%endif%}

                      <li>
                          <hr class="dropdown-divider">
                      </li>
                      {%endfor%}
                      {%endif%}
          
                      <!-- <li>
                        <hr class="dropdown-divider">
                      </li>
                      <li class="dropdown-footer">
                        <a href="#">Show all notifications</a>
                      </li> -->
          
                    </ul><!-- End Notification Dropdown Items -->
          
                  </li><!-- End Notification Nav -->


                <li class="nav-item dropdown pe-3">

                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <!-- <img src="assets/img/profile-img.jpg" alt="Profile" class="rounded-circle"> -->
                        <i class="bi bi-person"></i>
                        <!-- <span class="d-none d-md-block dropdown-toggle ps-2">NO.{{user.call_to_bar_number }}</span> -->
                    </a><!-- End Profile Iamge Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li class="dropdown-header">
                            <h6>{{user.first_name}} {{user.last_name}}</h6>
                            <span>{{user.role}}</span>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="/logout/">
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Sign Out</span>
                            </a>
                        </li>

                    </ul><!-- End Profile Dropdown Items -->
                </li><!-- End Profile Nav -->

            </ul>
        </nav><!-- End Icons Navigation -->

    </header><!-- End Header -->





    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">
    
          <li class="nav-item">
            <a class="nav-link " href="/">
              <i class="bi bi-grid"></i>
              <span>Dashboard</span>
            </a>
          </li><!-- End Dashboard Nav -->
    
          <li class="nav-item">
            <a class="nav-link" href="{% url 'case_urls:case' %}">
              <i class="bi bi-folder"></i>
              <span>Cases</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'message_urls:message' %}">
              <i class="bi bi-chat"></i>
              <span>Message</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'calendar_urls:calendar' %}">
              <i class="bi bi-calendar"></i>
              <span>Calender</span>
            </a>
          </li>
          <br><br>
         
          <li class="nav-item">
            <a class="nav-link" href="/settings/">
      
              <i class="bi bi-wrench"></i>
              <span>Settings</span>
            </a>
          </li>
    
    
        </ul>
    
      </aside>
    <!-- End Sidebar-->




    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Message</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Message</li>
                    <li class="breadcrumb-item active">Create</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->




        <!-- General Form Elements -->
        <div class="card">
            <div class="card-body p-5">

                <form method="post">
                    {% csrf_token %}
                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label">Select case :</label>
                        <div class="col-sm-10">
                            <select required  name="case_id" class="form-select" aria-label="Default select example">
                                {% for case in case%}
                                <option value="{{case.id}}" selected>{{case.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>


                    <div class="row mb-3">
                        <label for="inputText" class="col-sm-2 col-form-label">Title :</label>
                        <div class="col-sm-10">
                            <input name="title" type="text" required class="form-control">
                        </div>
                    </div>


                    <div class="row mb-3">
                        <label for="inputPassword" class="col-sm-2 col-form-label">Message :</label>
                        <div class="col-sm-10">
                            <textarea required name="message" class="form-control" style="height: 100px"></textarea>
                        </div>
                    </div>



                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Send Message <i class="bi bi-telegram"
                                    aria-hidden="true"></i> </button>
                        </div>
                    </div>
                </form>



            </div>
        </div>







    </main>
    <!-- End #main -->

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
        <div class="copyright">
            &copy; Copyright <strong><span>LEX-ATRIUM </span></strong>. All Rights Reserved
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <script src='{% static "vendor/bootstrap/js/bootstrap.bundle.js" %}'></script>
    <script src='{% static "vendor/jquery/jquery.min.js" %}'></script>
    <script src='{% static "vendor/select2/select2.min.js"  %}'></script>

    <script src='{% static "js/global.js" %}'></script>

    <script src='{% static "js/dashboard.js" %}'></script>



</body>

</html>